name: "Create k3d Cluster"
description: "Provision a local k3d Kubernetes cluster and expose KUBECONFIG"
author: "@jesus.rivera"

inputs:
  cluster-name:
    description: "Name of the k3d cluster"
    required: true
  k3d-config-template:
    description: "Path to the k3d config template file"
    required: true

outputs:
  kubeconfig-contents:
    description: "Raw kubeconfig content"
    value: ${{ steps.export-kubeconfig.outputs.kubeconfig-contents }}

runs:
  using: "composite"
  steps:
    - name: Install k3d
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        echo "k3d installed successfully"

    - name: Render k3d config file
      uses: nowactions/envsubst@v1
      with:
        input: ${{ inputs.k3d-config-template }}
        output: k3d-config.yaml
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}

    - name: Create cluster using rendered config
      shell: bash
      run: |
        k3d cluster create --config k3d-config.yaml

    - name: Export kubeconfig
      id: export-kubeconfig
      shell: bash
      run: |
        mkdir -p $HOME/.kube
        k3d kubeconfig get ${{ inputs.cluster-name }} > $HOME/.kube/config
        echo "kubeconfig-contents<<EOF" >> $GITHUB_OUTPUT
        cat $HOME/.kube/config >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT