name: "Create k3d Cluster"
description: "Provision a local k3d Kubernetes cluster and expose KUBECONFIG"
author: "@jesus.rivera"

inputs:
  cluster-name:
    description: "Name of the k3d cluster"
    required: true
  k3d-config:
    description: "k3d configuration for k3d cluster creation"
    required: true

outputs:
  kubeconfig-contents:
    description: "Raw kubeconfig content"
    value: ${{ steps.export-kubeconfig.outputs.kubeconfig-contents }}

runs:
  using: "composite"
  steps:
    - name: Install k3d
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    - name: Write k3d config to file
      shell: bash
      run: |
        cat <<EOF > k3d-config.yaml
        ${{ inputs.k3d-config }}
        EOF

    - name: Create cluster using config
      shell: bash
      run: |
        k3d cluster create ${{ inputs.cluster-name }} --config k3d-config.yaml
        
        # Verify cluster is running
        k3d cluster list
        
        # Quick connectivity test
        kubectl cluster-info --request-timeout=30s

    - name: Export kubeconfig
      id: export-kubeconfig
      shell: bash
      run: |
        echo "kubeconfig-contents<<EOF" >> $GITHUB_OUTPUT
        k3d kubeconfig get ${{ inputs.cluster-name }} >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT