name: CD

on:
  workflow_dispatch:

env:
  TF_VAR_database_name: ${{ vars.DATABASE_NAME }}
  TF_VAR_django_secret_key: ${{ secrets.DJANGO_SECRET_KEY }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  K3D_CONFIG: ${{ vars.K3D_CONFIG }}

jobs:
  deploy-app:
    name: Create Cluster and Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k3d cluster
        uses: ./.github/actions/create-k3d-cluster
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
          k3d-config: ${{ env.K3D_CONFIG }}

      - name: Verify k3d cluster
        run: |
 
          kubectl get all -A

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false -no-color
        env:
          KUBECONFIG: /home/runner/.kube/config
          TF_VAR_kubeconfig_path: /home/runner/.kube/config

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false
        env:
          KUBECONFIG: /home/runner/.kube/config
          TF_VAR_kubeconfig_path: /home/runner/.kube/config

      - name: Verify deployment
        run: |
          kubectl get pods -n devsu
          kubectl get svc -n devsu
          kubectl get ingress -n devsu

      - name: Test application
        run: |
          # Example of accessing the API endpoint - at this point, there's no user created
          # so it should return an empty list
          curl http://localhost/api/users/

          # Example of creating a user via the API
          curl -X POST http://localhost/api/users/ \
          -H "Content-Type: application/json" \
          -d '{"dni": "123456789", "name": "Jesus Rivera"}'
          
          # Show new added user
          curl http://localhost/api/users/