name: CD

on:
  workflow_dispatch:

env:
  TF_VAR_database_name: ${{ vars.DATABASE_NAME }}
  TF_VAR_django_secret_key: ${{ secrets.DJANGO_SECRET_KEY }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  K3D_CONFIG: ${{ vars.K3D_CONFIG }}

jobs:
  deploy-app:
    name: Create Cluster and Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k3d cluster
        uses: ./.github/actions/create-k3d-cluster
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
          k3d-config: ${{ env.K3D_CONFIG }}

      - name: Verify k3d cluster
        run: |
          kubectl get all -A

      # Deploy the application using Terraform
      - name: Terraform Deploy
        uses: ./.github/actions/terraform-deploy
        with:
          kubeconfig-path: /home/runner/.kube/config
          apply: ${{ github.ref == 'refs/heads/main' }}
      - name: Verify deployment
        run: |
          kubectl get pods -n devsu
          kubectl get svc -n devsu
          kubectl get ingress -n devsu

      - name: Test application
        run: |
          # Example of accessing the API endpoint - at this point, there's no user created
          # so it should return an empty list
          echo "GET /api/users/ (should be empty)"
          curl -s http://localhost/api/users/
          echo -e "\n---"

          # Example of creating a user via the API
          echo "POST /api/users/ (create new user)"
          curl -s -X POST http://localhost/api/users/ \
          -H "Content-Type: application/json" \
          -d '{"dni": "123456789", "name": "Jesus Rivera"}'
          echo -e "\n---"
          
          # Show new added user
          echo "GET /api/users/ (should list the created user)"
          curl -s http://localhost/api/users/
          echo