name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened]
    paths:
      - '**.py'
      - Dockerfile
      - '.github/workflows/ci.yaml'
      - 'requirements.txt'

# Permissions required for the workflow to push Docker images to the GitHub Container Registry and other actions
permissions:
  contents: read
  packages: write
  security-events: write
  pull-requests: write

env:
    IMAGE_NAME: ghcr.io/${{ github.repository }}
    IMAGE_TAG: ${{ github.sha }}
    PYTHON_VERSION: 3.11.3

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}} 
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage flake8 bandit

      # Django tests and coverage
      - name: Run Django tests and coverage
        run: |
          python -m coverage run manage.py test
          python -m coverage xml

      # Storage of coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
            name: coverage-report
            path: coverage.xml
        
      - name: Cobertura coverage check
        uses: 5monkeys/cobertura-action@master
        with:
            path: coverage.xml
            minimum_coverage: 80
            show_branch: true
            report_name: django-coverage-report

    #     # --- Security checks --- 
    #   - name: Run security checks
    #     run: |
    #       bandit -r api tests
