name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened]
    paths:
      - "**.py"
      - Dockerfile
      - ".github/workflows/ci.yaml"
      - "requirements.txt"

# Permissions required for the workflow to push Docker images to the GitHub Container Registry and other actions
permissions:
  contents: read
  packages: write
  security-events: write
  pull-requests: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
  PYTHON_VERSION: 3.11.3

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage flake8 bandit

        # Django tests and coverage
      - name: Run Django tests and coverage
        run: |
          python -m coverage run manage.py test
          python -m coverage xml

      - name: Upload coverage XML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      # Run only on pull requests
      - name: Cobertura coverage check
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: 5monkeys/cobertura-action@v14
        with:
          path: coverage.xml
          minimum_coverage: 80
          fail_below_threshold: false
          skip_covered: true
          only_changed_files: true
          show_line: true
          show_branch: true
          show_missing: true
          show_missing_max_length: 120
          link_missing_lines: true
          report_name: django-coverage

      # Run Coding Style Checks
      - name: Run flake8 linter code style check
        run: |
          flake8 -q --count --statistics --ignore=E,F,W api

      # Run Python security checks
      - name: Run bandit security check
        uses: PyCQA/bandit-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
