name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
      - Dockerfile
      - '.github/workflows/ci.yaml'
      - 'requirements.txt'

permissions:
  contents: read
  packages: write
  security-events: write

env:
    IMAGE_NAME: ghcr.io/${{ github.repository }}
    IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 bandit

      - name: Run tests
        run: |
          pytest